### ISSUE TITLE
Create cut-maker orchestrator

### ISSUE THREAD

**Issue by williamokano** [williamokano/youtube-cut-maker-bot#6]
Requirements:
- [ ] Download bot implemented (https://github.com/williamokano/youtube-cut-maker-bot/issues/2)  
- [ ] Cut bot implemented (https://github.com/williamokano/youtube-cut-maker-bot/issues/3)  
- [ ] Upload bot implemented (https://github.com/williamokano/youtube-cut-maker-bot/issues/5)  

Nice to have:
- [ ]  Merge bot implemented (https://github.com/williamokano/youtube-cut-maker-bot/issues/4)  

This bot should should orchestrate all the other bots, and get all the required parameters. Should also decide whether or not call merge bot (if user decide to have channel introduction or channel endings, for example), and merge the video before uploading it.

Should ask for all required parameters, such as `url`, `title`, `start`, `end`, and optional parameters, such as `description` and `tags`.
